version: "3"

services:
  phx_db:
    image: postgres
    container_name: phx_db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=phx
      - POSTGRES_PASSWORD=postgres
